<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PoolGame.Tools.Visualizer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../core/PoolGame.Core/PoolGame.Core.csproj" />
  </ItemGroup>
</Project>
